/****** Objecto:  Base de Datos ******/
CREATE DATABASE epn_InventarioEquipos_Historico
GO
USE epn_InventarioEquipos_Historico
GO

/****** Objecto:  Esquemas ******/
CREATE SCHEMA [bajas]
GO

CREATE SCHEMA [compra]
GO

CREATE SCHEMA [mantenimiento]
GO

CREATE SCHEMA [registro]
GO

/****** Objecto:  Tablas ******/
CREATE TABLE [compra].[PROVEEDOR](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL,
	[apellido] [nchar](25) NOT NULL)
GO

CREATE TABLE [mantenimiento].[ESTADO_EQUIPO](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL)
GO

CREATE TABLE [mantenimiento].[MANTENIMIENTO](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[idTipoMantenimiento] [int] NOT NULL,
	[idEquipo] [int] NOT NULL,
	[idTecnico] [int] NOT NULL,
	[fechaMantenimiento] [date] NOT NULL)
GO

CREATE TABLE [mantenimiento].[MANTENIMIENTO_REEMPLAZO_COMPONENTES](
	[idMantenimiento] [int] NOT NULL PRIMARY KEY,
	[idComponenteReemplazado] [int] NOT NULL,
	[observaciones] [nchar](50) NOT NULL)
GO

CREATE TABLE [mantenimiento].[TECNICO](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL,
	[apellido] [nchar](25) NOT NULL)
GO

CREATE TABLE [mantenimiento].[TIPO_MANTENIMIENTO](
	[int] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL)
GO

CREATE TABLE [registro].[ASIGNACION](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[idEquipo] [int] NOT NULL,
	[idResponsable] [int] NOT NULL,
	[fechAsignacion] [date] NOT NULL,
	[activo] [bit] NOT NULL)
GO

CREATE TABLE [registro].[COMPONENTES](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[idEquipo] [int] NOT NULL,
	[idTipoComponente] [int] NOT NULL)
GO

CREATE TABLE [registro].[EQUIPO](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[idEstado] [int] NOT NULL,
	[idProveedor] [int] NOT NULL,
	[idTipoEquipo] [int] NOT NULL,
	[marca] [nchar](25) NOT NULL,
	[modelo] [nchar](25) NOT NULL,
	[fechaCompra] [date] NOT NULL,
	[valorCompra] [money] NOT NULL)
GO

CREATE TABLE [registro].[RESPONSABLE](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL,
	[apellido] [nchar](25) NOT NULL)
GO

CREATE TABLE [registro].[TIPO_COMPONENTE](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL)
GO

CREATE TABLE [registro].[TIPO_EQUIPO](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[nombre] [nchar](25) NOT NULL)
GO

/****** Actualizaciones en Cascada ******/

ALTER TABLE [mantenimiento].[MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_MANTENIMIENTO_EQUIPO] FOREIGN KEY([idEquipo])
REFERENCES [registro].[EQUIPO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [mantenimiento].[MANTENIMIENTO] CHECK CONSTRAINT [FK_MANTENIMIENTO_EQUIPO]
GO

ALTER TABLE [mantenimiento].[MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_MANTENIMIENTO_TECNICO] FOREIGN KEY([idTecnico])
REFERENCES [mantenimiento].[TECNICO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [mantenimiento].[MANTENIMIENTO] CHECK CONSTRAINT [FK_MANTENIMIENTO_TECNICO]
GO

ALTER TABLE [mantenimiento].[MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_MANTENIMIENTO_TIPO_MANTENIMIENTO] FOREIGN KEY([idTipoMantenimiento])
REFERENCES [mantenimiento].[TIPO_MANTENIMIENTO] ([int])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [mantenimiento].[MANTENIMIENTO] CHECK CONSTRAINT [FK_MANTENIMIENTO_TIPO_MANTENIMIENTO]
GO

ALTER TABLE [mantenimiento].[MANTENIMIENTO_REEMPLAZO_COMPONENTES]  WITH NOCHECK ADD  CONSTRAINT [FK_MANTENIMIENTO_REEMPLAZO_COMPONENTES_COMPONENTES] FOREIGN KEY([idComponenteReemplazado])
REFERENCES [registro].[COMPONENTES] ([id])
NOT FOR REPLICATION 
GO
ALTER TABLE [mantenimiento].[MANTENIMIENTO_REEMPLAZO_COMPONENTES] NOCHECK CONSTRAINT [FK_MANTENIMIENTO_REEMPLAZO_COMPONENTES_COMPONENTES]
GO

ALTER TABLE [mantenimiento].[MANTENIMIENTO_REEMPLAZO_COMPONENTES]  WITH CHECK ADD  CONSTRAINT [FK_MANTENIMIENTO_REEMPLAZO_COMPONENTES_MANTENIMIENTO] FOREIGN KEY([idMantenimiento])
REFERENCES [mantenimiento].[MANTENIMIENTO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [mantenimiento].[MANTENIMIENTO_REEMPLAZO_COMPONENTES] CHECK CONSTRAINT [FK_MANTENIMIENTO_REEMPLAZO_COMPONENTES_MANTENIMIENTO]
GO

ALTER TABLE [registro].[ASIGNACION]  WITH CHECK ADD  CONSTRAINT [FK_ASIGNACION_EQUIPO] FOREIGN KEY([idEquipo])
REFERENCES [registro].[EQUIPO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[ASIGNACION] CHECK CONSTRAINT [FK_ASIGNACION_EQUIPO]
GO

ALTER TABLE [registro].[ASIGNACION]  WITH CHECK ADD  CONSTRAINT [FK_ASIGNACION_RESPONSABLE] FOREIGN KEY([idResponsable])
REFERENCES [registro].[RESPONSABLE] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[ASIGNACION] CHECK CONSTRAINT [FK_ASIGNACION_RESPONSABLE]
GO

ALTER TABLE [registro].[COMPONENTES]  WITH CHECK ADD  CONSTRAINT [FK_COMPONENTES_EQUIPO] FOREIGN KEY([idEquipo])
REFERENCES [registro].[EQUIPO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[COMPONENTES] CHECK CONSTRAINT [FK_COMPONENTES_EQUIPO]
GO

ALTER TABLE [registro].[COMPONENTES]  WITH CHECK ADD  CONSTRAINT [FK_COMPONENTES_TIPO_COMPONENTE] FOREIGN KEY([idTipoComponente])
REFERENCES [registro].[TIPO_COMPONENTE] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[COMPONENTES] CHECK CONSTRAINT [FK_COMPONENTES_TIPO_COMPONENTE]
GO

ALTER TABLE [registro].[EQUIPO]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPO_ESTADO_EQUIPO1] FOREIGN KEY([idEstado])
REFERENCES [mantenimiento].[ESTADO_EQUIPO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[EQUIPO] CHECK CONSTRAINT [FK_EQUIPO_ESTADO_EQUIPO1]
GO

ALTER TABLE [registro].[EQUIPO]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPO_PROVEEDOR] FOREIGN KEY([idProveedor])
REFERENCES [compra].[PROVEEDOR] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[EQUIPO] CHECK CONSTRAINT [FK_EQUIPO_PROVEEDOR]
GO

ALTER TABLE [registro].[EQUIPO]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPO_TIPO_EQUIPO] FOREIGN KEY([idTipoEquipo])
REFERENCES [registro].[TIPO_EQUIPO] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [registro].[EQUIPO] CHECK CONSTRAINT [FK_EQUIPO_TIPO_EQUIPO]
GO

/****** Seleccion de las tablas ******/
SELECT * FROM compra.PROVEEDOR
SELECT * FROM mantenimiento.ESTADO_EQUIPO
SELECT * FROM mantenimiento.MANTENIMIENTO
SELECT * FROM mantenimiento.MANTENIMIENTO_REEMPLAZO_COMPONENTES
SELECT * FROM mantenimiento.TECNICO
SELECT * FROM mantenimiento.TIPO_MANTENIMIENTO
SELECT * FROM registro.ASIGNACION
SELECT * FROM registro.COMPONENTES
SELECT * FROM registro.EQUIPO
SELECT * FROM registro.RESPONSABLE
SELECT * FROM registro.TIPO_COMPONENTE
SELECT * FROM registro.TIPO_EQUIPO

/****** Insercion de datos ******/

INSERT INTO compra.PROVEEDOR VALUES('Jose','Ayala')
INSERT INTO compra.PROVEEDOR VALUES('Maria','Aldaz')
INSERT INTO compra.PROVEEDOR VALUES('Bryan','Cruz')

INSERT INTO registro.TIPO_EQUIPO VALUES('Computador de Escritorio')
INSERT INTO registro.TIPO_EQUIPO VALUES('Impresora')
INSERT INTO registro.TIPO_EQUIPO VALUES('Proyector')

INSERT INTO mantenimiento.TECNICO VALUES('Pablo','Teran')
INSERT INTO mantenimiento.TECNICO VALUES('Susana','Garcia')
INSERT INTO mantenimiento.TECNICO VALUES('Ambar','Lescano')

INSERT INTO registro.RESPONSABLE VALUES('Marco','Perez')
INSERT INTO registro.RESPONSABLE VALUES('Lorena','Palomino')
INSERT INTO registro.RESPONSABLE VALUES('Iris','Castro')

INSERT INTO mantenimiento.ESTADO_EQUIPO VALUES('Bueno')
INSERT INTO mantenimiento.ESTADO_EQUIPO VALUES('En Reparacion')
INSERT INTO mantenimiento.ESTADO_EQUIPO VALUES('Malo')
INSERT INTO mantenimiento.ESTADO_EQUIPO VALUES('Baja')

INSERT INTO mantenimiento.TIPO_MANTENIMIENTO VALUES ('Preventivo')
INSERT INTO mantenimiento.TIPO_MANTENIMIENTO VALUES ('Correctivo')

INSERT INTO registro.TIPO_COMPONENTE VALUES('Memoria')
INSERT INTO registro.TIPO_COMPONENTE VALUES('Fuente de Poder')
INSERT INTO registro.TIPO_COMPONENTE VALUES('Disco Duro')

                   	   		
